### ISSUE TITLE
Nonlinear transform meta-issue

### ISSUE THREAD

**Issue by asinghvi17** [JuliaPlots/Makie.jl#595]
# User experience
- [ ] Create a wrapper type to allow arbitrary transformations, which act on all coordinates.
- [ ] Document `apply_transform`, and how to overload it ([existing methods are here](https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/layouting/transformation.jl#L210-L245))
- [ ] Create wrapper trait types (`TransformFunc{2D}`, `TransformFunc{NeedsXY}`, etc)
# Low level features
- [ ] Make heatmap, surface, mesh, volume, etc work with nonlinear transforms

**Comment by ffreyer** [comment]
Is this still useful or can we close this?

**Comment by asinghvi17** [comment]
Probably still useful though I need to update it.  Ideally transforms just subscribe to a trait like interface so we don't need to wrap everything in Makie.PointTrans...
